### ISSUE TITLE
Less code repetition in XRechnungMapping.hpp  for some structure declarations

### ISSUE THREAD

**Issue by Yaraslaut** [LASTRADA-Software/XRechnung#1]
It is possible to abstract away creation of such structures
```
struct ItemOriginCountryCode final {
  static constexpr std::u8string_view id{u8"BT-159"};
  static constexpr std::u8string_view path{u8"cbc:IdentificationCode"};
  XDataTypes::Code type;

  [[nodiscard]] bool isValid() const { return !type.content.empty(); }
};
```
with the following code
```
using NewItemOriginCountryCode = entry<Id<u8"BT-159">, Path<u8"cbc:IdentificationCode">, XDataTypes::Code>;
```
Here is a godbolt link with example and a case with additional field `outerPath` https://godbolt.org/z/n3P74fhG5

**Comment by FelixTheC** [comment]
Feel free to create a PR with your changes.

@Yaraslaut I hope my sentence was not misleading cause I'm really looking forward to see your changes in a PR.

**Comment by Yaraslaut** [comment]
> Feel free to create a PR with your changes.
> 
> @Yaraslaut I hope my sentence was not misleading cause I'm really looking forward to see your changes in a PR.

No worries, I will make a PR later today :)
