### ISSUE TITLE
BuyerContactEMail::id

### ISSUE THREAD

**Issue by Yaraslaut** [LASTRADA-Software/XRechnung#3]
While refactoring code i noticed following lines 
```
    struct BuyerContactTelephone final {
        static constexpr std::u8string_view id{u8"BT-57"};
....
    };

    struct BuyerContactEMail final {
        static constexpr std::u8string_view id{u8"BT-57"};
...
    };


```
I suppose `BuyerContactEMail` should be with `BT-58` id

**Comment by FelixTheC** [comment]
Thanks for finding this. Would you maybe fix this in your refactoring branch?

**Comment by Yaraslaut** [comment]
> Thanks for finding this. Would you maybe fix this in your refactoring branch?

Hi, yes, I will fix it there 
Just wanted to make sure that this is not expected
